version: "3.9"

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=${DBNAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      - karma8-network

  rabbit:
    build:
      context: ./docker/rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    ports:
      - '127.0.0.1:15672:15672'
      - '127.0.0.1:5672:5672'
    networks:
      - karma8-network

  redis:
    image: redis:7-alpine
    networks:
      - karma8-network

  php:
    build:
      args:
        UID: ${USERID}
        GID: ${GROUPID}
      context: ./docker/php
    user: ${USERID}:${GROUPID}
    working_dir: '/var/www/karma8'
    env_file:
      - ./.env
    restart: always
    volumes:
      - './:/var/www/karma8'
      - './log:/var/www/karma8/log'
    depends_on:
      - redis
      - rabbit
      - db
    networks:
      - karma8-network

networks:
  karma8-network:
    external: true
