version: "3.9"

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=${DBNAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - karma8-network

  php:
    build:
      args:
        UID: ${USERID}
        GID: ${GROUPID}
      context: ./docker/php
    user: ${USERID}:${GROUPID}
    working_dir: '/var/www/karma8'
    env_file:
      - ./.env
    restart: always
    volumes:
      - './:/var/www/karma8'
    networks:
      - karma8-network

networks:
  karma8-network:
    external: false
